### PR TITLE
Add streaming log

### PR DESCRIPTION
**Pull request by maxnoe**
Implements a log endpoint for logged in users which streams the shifthelper logfile as given in the config. To avoid to much traffic, at first only the first 100 lines are send.

### CODE REVIEW

**Comment by dneise** [comment]
Do I understand correctly that gunicorn replaces nginx? if so, does this have an impact on deployment? I mean, in case one wants to test locally ...

**Comment by maxnoe** [comment]
Currently we still use nginx as ssl endpoint in deployment.
But I think this could be dropped, let me investigate.

Current setup in the docker stuff: `nginx` as ssl endpoint, proxy to `gunicorn` which uses `eventlet` to spawn our flask app.

**Comment by maxnoe** [comment]
Ah, okay. So I have no real idea why, but it's the recommended way to have gunicorn run behind a reverse proxy like a simple nginx:

http://docs.gunicorn.org/en/stable/deploy.html

**Comment by dneise** [comment]
sounds pretty complicated for a noob like me .... I mean complicated to find out, set up and get to run, but now since you did all that already ... I think its cool.

**Comment by maxnoe** [comment]
Which was basically copy paste of the examples found here: https://flask-socketio.readthedocs.io/en/latest/

For local testing it suffices to do
```
gunicorn -k eventlet shifthelper_webinterface:app
```
I will update the README when I find the time.

**Comment by maxnoe** [comment]
Here is a nice  answer explaining the nginx + gunicorn stuff http://serverfault.com/questions/331256/why-do-i-need-nginx-and-something-like-gunicorn

**Comment by dneise** [comment]
Thanks, very nice read

**Comment by dneise** [comment]
Can you point out a little more, what in this PR solves: #22 and and fact-project/shifthelper#228 ?

**Comment by maxnoe** [comment]
It's the last commit. Sorry,  does not really belong here but was a hotfix on the weekend, so ...

**Pull request merged**
